### PR TITLE
Domainic command/feature/add and then method

### LINKED ISSUE #176: Add chainable results with and_then support
## Description

Add support for chaining command executions using an `and_then` method on the Result object. This provides a clean, functional approach to command composition without the complexity of dedicated organizers.

## Current Behavior

Commands must be called individually with explicit error handling between each call:

```ruby
result = CreateUser.call(name: "John")
return result unless result.successful?

result = SendWelcomeEmail.call(user_id: result.user.id)
return result unless result.successful?

NotifyAdmin.call(user_id: result.user.id)
```

## Desired Behavior

Allow chaining of commands using `and_then`:

```ruby
CreateUser.call(name: "John")
  .and_then { |r| SendWelcomeEmail.call(user_id: r.user.id) }
  .and_then { |r| NotifyAdmin.call(user_id: r.user.id) }
```

* Chain stops executing if any command fails
* Each successful command's result is passed to the next block
* Final result includes data from entire chain
* Maintains explicit data flow between commands
* Thread safe

## Testing Requirements

* Test chain execution stops on failure
* Test data passing between chain steps
* Test final result contains complete chain data
* Test error handling and status codes
* Test thread safety

## Related Components

* `Domainic::Command::Result`
* `Domainic::Command::Result::ErrorSet`

### PR DESCRIPTION
**Pull request by shouya31**
## Description
This PR adds the and_then method to the Domainic::Command::Result class, enabling a functional and chainable approach to handling command results. This simplifies the process of chaining commands and reduces boilerplate code for error handling.

## Related Issues
Fixes #176

## Checklist

Before submitting this PR, please ensure:
* [x] I have run `bin/dev ci` and all checks pass
* [x] I have added/updated tests that prove my fix/feature works
* [x] I have added/updated documentation as needed

## Additional Notes

**Implementation Details**
- The and_then method ensures a safe and predictable flow of command chaining.
- If the block does not return a Result, the chain is terminated with the original result.

**Functional Validation**
The following example was tested successfully in irb:
```rb
result = Domainic::Command::Result.success(value: 42)
chained_result = result
  .and_then { |r| Domainic::Command::Result.success(value: r.value * 2) }
  .and_then { |r| Domainic::Command::Result.success(value: r.value + 10) }

puts chained_result.successful? # => true
puts chained_result.value       # => 94
```

**Failure Handling Validation**
```rb
result = Domainic::Command::Result.failure({ error: 'initial failure' })
chained_result = result.and_then { |r| Domainic::Command::Result.success(value: r.value * 2) }

puts chained_result.failure?          # => true
puts chained_result.errors[:error]    # => ["initial failure"]
```

**Exception in Block:**
```rb
result = Domainic::Command::Result.success(value: 42)

# Chain with a block that raises an exception
begin
  result.and_then { |_r| raise "Unexpected error" }
rescue => e
  puts e.message  # => "Unexpected error"
end
```

### CODE REVIEW

File: domainic-command/lib/domainic/command/result.rb [hunk 1]
```diff
@@ -121,6 +121,34 @@ def initialize(status_code, context: {}, errors: nil)
...
+      # @return [Result] The new result object if successful, or the current result if failed.
+      # @rbs () { (self) -> self } -> self
+      def and_then
+        return self if failure?
+
+        new_result = yield(self)
+
+        unless new_result.is_a?(self.class)
+          raise TypeError, "Block must return a #{self.class}, got #{new_result.class}"
+        end
```
Comment (shouya31) [inline domainic-command/lib/domainic/command/result.rb:147]: I’ve updated the and_then method to raise an exception when the block returns a non-Result object. Could you confirm if treating other objects as exceptions aligns with our intended behavior?

 If there are any specific scenarios or use cases where this approach might be problematic, please let me know so we can adjust accordingly.

**Comment by shouya31** [comment]
##MEMO: Requirements
### Chaining Commands with and_then
- [ ] The and_then method enables chaining of commands, passing successful results to subsequent blocks while stopping execution on failure.

Example:
```fb
CreateUser.call(name: "John")
.and_then { |r| SendWelcomeEmail.call(user_id: r.value) }
.and_then { |r| NotifyAdmin.call(user_id: r.value) }
```
**Stopping Execution on Failure**
- [ ]  If the current result is not successful, the original failure result is returned immediately, and subsequent blocks are not executed.
**Passing Data Between Commands**
- [ ]  Successful results are passed as arguments to the next block, maintaining explicit data flow.
**Final Result Reflects Chain**
- [ ]  The final result reflects the output of the last successful command or the first failure in the chain.
**Maintaining Explicit Data Flow**
- [ ]  The result is explicitly passed to each block, ensuring clarity in data handling.
**Thread Safety**
- [ ]  The current implementation does not explicitly guarantee thread safety. Additional mechanisms are needed for safe usage in concurrent contexts.

### Testing Requirements
**Execution Stops on Failure**
- [ ]  Chains stop execution when any command fails, with subsequent blocks skipped. This behavior is confirmed in tests.
**Data Passing Between Commands**
- [ ]  Data from each successful command is correctly passed to the next block, as verified by tests.
**Final Result Includes Chain Data**
- [ ]  The final result contains either the output of the last successful command or the first failure, as tested.
**Error Handling and Status Codes**
- [ ]  Success and failure states are clearly distinguished, with status codes handled appropriately in tests.
**Thread Safety**
- [ ]  There are no tests for thread safety. If concurrency is a concern, explicit synchronization mechanisms and corresponding tests are required.

**Comment by aaronmallen** [comment]
I'm not super concerned about the thread safety bit atm, that's honestly a "nice to have". I'm going to go through the entire thing with a fine toothed comb at a later date and ensure everything is thread safe. I'm actually pretty happy with this implementation. When you're ready to convert it from a draft please rebase it on top of the latest main as I have fixed the CI failure issue in #195

File: domainic-command/lib/domainic/command/result.rb [hunk 2]
```diff
@@ -121,6 +121,29 @@ def initialize(status_code, context: {}, errors: nil)
...
+      #              .and_then { |r| SendWelcomeEmail.call(user_id: r.user[:id]) }
+      #              .and_then { |r| NotifyAdmin.call(user_id: r.user[:id]) }
+      #
+      # @yield [result] Provides the current successful result to the block.
+      # @yieldparam [Result] result The current successful result object.
+      # @yieldreturn [Object] Any object resulting from the block.
+      #
+      # @return [Object] The new result or output object, or the current result if failed.
+      # @rbs () { (self) -> self } -> self
+      def and_then
```
Comment (aaronmallen) [inline domainic-command/lib/domainic/command/result.rb:141]: I know this is a draft but before you get much further; Let's make this `then` and alias it as `and_then`.

File: domainic-command/spec/domainic/command/result_spec.rb [hunk 3]
```diff
@@ -37,6 +37,35 @@
     end
   end
 
+  describe '#and_then', rbs: :skip do
```
Comment (aaronmallen) [inline domainic-command/spec/domainic/command/result_spec.rb:40]: I don't remember why I'm skipping RBS in all of these examples. Can you remove this tag and confirm these specs actually fail on `bin/dev test --rbs`? If they do fail then cool we'll keep the tag, but I'd rather not have it if we don't need it.

**Review by aaronmallen — CHANGES_REQUESTED** [review]

File: domainic-command/spec/domainic/command/result_spec.rb (hunk 3 above)
Comment (shouya31) [reply domainic-command/spec/domainic/command/result_spec.rb]: Fix https://github.com/domainic/domainic/pull/194/commits/73aa9d46b4d010d00e956a480491c3c38d9948b4

You're right, this option wasn't necessary. The tests didn't fail after removing it, so I'll go ahead and remove it.

File: domainic-command/lib/domainic/command/result.rb (hunk 2 above)
Comment (shouya31) [reply domainic-command/lib/domainic/command/result.rb]: FIx https://github.com/domainic/domainic/pull/194/commits/8eeacfa3097bc30167cccedc9d39b34af18f6719

**Comment by shouya31** [comment]
@aaronmallen 
> I'm not super concerned about the thread safety bit atm, that's honestly a "nice to have". I'm going to go through the entire thing with a fine toothed comb at a later date and ensure everything is thread safe. I'm actually pretty happy with this implementation.

Understood about the thread safety background! In that case, I'll proceed with the review request without implementing it in this PR.

**Review by aaronmallen — APPROVED** [review]

**Comment by aaronmallen** [comment]
Thanks so much @shouya31 also give #196 a look when you get the chance.
